version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dreamsync-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dreamsync-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dreamsync-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dreamsync-network

networks:
  dreamsync-network:
    driver: bridge
