version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dreamsync-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/backend/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dreamsync-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:80"

